### PR TITLE
Write intro to backend documentation

### PR DESCRIPTION
**Pull request by Baltoli**
This PR adds a high-level overview of the backend's structure and flows of data to the new documentation.

### CODE REVIEW

**Comment by Robertorosmaninho** [comment]
Hey @Baltoli, thanks for the documentation! Just a minor comment, the arrows on the images are hard to see using GitHub's dark mode. Can the color or the arrow outline be changed?

**Comment by Baltoli** [comment]
Good catch @Robertorosmaninho - will update the drawings!

**Review by Robertorosmaninho — APPROVED** [review]
LGTM!

**Review by dwightguth — APPROVED** [review]
This looks good, but I would suggest replacing the DOI link for the maranget paper with the actual full text PDF link.

**Pull request merged**
