### PR TITLE
Deleting coreutils dependence and replacing its `uname` by `$OSTYPE` bash var

### PR DESCRIPTION
**Pull request by Robertorosmaninho**
Fixes: #834

### CODE REVIEW

**Comment by Baltoli** [comment]
This seems like a potentially much more fragile solution than having a dependency on coreutils. What's the motivation for removing the dependency?

**Comment by Robertorosmaninho** [comment]
> This seems like a potentially much more fragile solution than having a dependency on coreutils. What's the motivation for removing the dependency?

There are two reasons to delete `coreutils` dependence:
1. It is only used by `uname` and only once. Many examples in the source code use `$OSTYPE` instead of `uname`.
2. MacOS has a built-in `uname` binary; we can use it if necessary, right? 


I can't really tell the reason why a shell variable would be much more fragile than the system call, but if that's necessary, I can do the other way around in a future PR and replace all `$OSTYPE` comparisons with `uname` ones.

**Comment by gtrepta** [comment]
Some more instances of coreutils that haven't been removed:

https://github.com/runtimeverification/llvm-backend/blob/11b4a5727858f2a6a452673cbd97906dfc1000d4/nix/llvm-backend.nix#L1

https://github.com/runtimeverification/llvm-backend/blob/11b4a5727858f2a6a452673cbd97906dfc1000d4/INSTALL.md?plain=1#L34-L38

**Comment by Robertorosmaninho** [comment]
Thanks @gtrepta!

**Comment by radumereuta** [comment]
I don't feel confident reviewing this since I don't own a Mac.
I think @goodlyrottenapple uses one.

**Review by dwightguth — APPROVED** [review]

**Pull request merged**
